service: neo-qrcode

plugins:
    - serverless-apigw-binary
    - serverless-apigwy-binary

custom:
    apigwBinary:
        types:
            - 'image/jpeg'

provider:
    name: aws
    region: ap-northeast-1
    runtime: nodejs6.10

functions:
    hello:
        handler: handler.hello
        events:
            - http:
                  path: /{address}
                  method: get
                  contentHandling: CONVERT_TO_BINARY
